---
title: "Christophe Patterson CV"
author: ''
date: "29/06/2023"
output:
  #html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

**Uni email:** [christophe.patterson\@durham.ac.uk](mailto:christophe.patterson@durham.ac.uk){.email}

**Personal email** : [christophepatterson\@outlook.com](mailto:christophepatterson@outlook.com){.email}

------------------------------------------------------------------------

### Personal Profile

A PhD student with a passion for exploration and education. Has a keen interest in studying the impacts of humans actions, including climate change, on biodiversity and species geographic ranges. Interested in furthering their experience in next generation sequencing, fieldwork, scientific literacy, and communication. Has developed the key skills needed for teamwork and effective organisation across a diverse range of jobs and voluntary work.

------------------------------------------------------------------------

### Education

**Durham University**: 2020 to Present

|       **PhD - Durham Doctoral Studentship**

Doctoral student within the Bioscience department studying how interactions between species impact range expansion. Primarily working on landscape genomics of Rubyspot damselflies (*Hetaerina*). Wet lab experience organising and processing samples (\>400) for DNA extraction. Six weeks training at the NERC Environmental Omics Facility learning to carry out ddRAD sequencing. Tropical fieldwork in Mexico, surveying, collecting, photographing, and running behavioural experiments on damselflies along rivers. Member of the Graduate Liaison Committee listening to and providing feedback on ideas to improve the experience of PhD students at Durham.

**University of Exeter (Penryn Campus)**: 2018 to 2020

|       **Master by Research in Biological sciences**

Research degree investigating the range expansion of a species of hermit crab to the UK. Conducting data collection in the UK and France followed by DNA extraction, sequencing, and analysis of population genetics and phylogeography. Additional work conducting larval dispersal models. Work also includes demonstrating and marking on undergraduate and taught masters modules, including Analysis of Biological Data, Introduction to Invertebrates, and Key Skills in Biology. This all balanced with working a part time retail job as well as a Meta-analysis in artificial light at night. Member of the organising committee for **BES Macroecology Special Interest Group** 2019 conference helping with the planning, organising, and running of a 3-day scientific conference. See publications section below.

|       **Bachelor of Science with Honours in Evolutionary Biology: First Class** 2015 to 2018

Selected modules results: \| **Third year** - Research project, Borneo Field Course, Science in Society (all 1st), Marine spatial ecology (2:1) \| *Awarded the Sir Geoffrey Holland Prize for academic excellence within a field related to Cornwall* \| **Second year** - Iceland field Course, Analysis of Biological Data, Evolutionary Conservation Genetics, and Mathematics of the Environment II (all 1st), Exploitation of the Sea (2.1) \| **First year** - Genetics, and Physiology (1st). Conservation and Ecology, Evolutionary and Behavioural Ecology, Field and lab techniques, and Key Skills in biology (all 2.1)

<center>

*Terrifically good writing, a real pleasure to read.* - Professor Michael Cant

*Excellent personal writing style that draws the reader in, beautifully written.* -- Dr R. Early & Dr K. Moyes

</center>

| 
| 

**University of California, Berkeley:** July to August 2017

Awarded a bursary to fund six weeks study abroad in Berkeley, California. Living and working with students from across the globe. Studied: Selected Topics in Astronomy (A-), and Introduction to Oceanography (B).

**Prince Henry's Grammar School & Sixth Form:** 2007 to 2015

A Levels in Biology (A), Art (A), and Physics (B), with AS Level Mathematics (C). 12 GCSEs; 4 A\*s in Biology, Physics, Chemistry and Art, A in Mathematics, 5 Bs including Further Mathematics and English Language. 2 Cs and 1 D.

------------------------------------------------------------------------

### Publications

**Patterson C** and Drury J. Interspecific behavioural interference and range dynamics: current insights and future directions *Biological Reviews* 2023

**Patterson C** , Laing C, Early R. The range expansion of *Clibanarius erythropus* to the UK suggests that other range-shifting intertidal species may not follow *Marine Biology* 2022

**Patterson C** , Slater M, Early R, Laing C. The status of *Clibanarius erythropus* after a recent range expansion to Great Britain, with the highest latitude recording of a gravid individual. *Marine Biology Records.* 2020

Sanders D, Frago E, Kehoe R, **Patterson C**, and Gaston KJ. . A meta-analysis of biological impacts of artificial light at night. *Nature Ecology & Evolution* 2021

**Patterson C,** Early R, Lowe C. The hermit crab *Clibanarius erythropus* shows little phylogeographic structure across the European seascape [In revision]

------------------------------------------------------------------------

### Awards and Grants

-   **Durham Doctoral Studentship** Durham University, Oct 2020 – March 2024 - £68,250
-   **Sir Geoffrey Holland Prize for academic excellence within a field related to Cornwall** University of Exeter, 2018- £500 
-   **Heredity Fieldwork Grant** Genetics society, 2018 - £1500

------------------------------------------------------------------------

### Previous/Current Employment and Voluntary Work

**Director, The Rockpool Project:** July 2018 to present

Director of the not-for-profit for a community outreach project aiming to educate, engage and conserve rock pool wildlife in the UK. Responsible for giving half an hour educational talk to people of multiple ages and an hour and a half personal guides for groups, both involving answering questions about a wide range of littoral flora. Requiring organisation and speed to set up and back down equipment around the tide. Co-host of the six week course "Introduction to rock pooling" an online lecture series. Additional full time six-week paid internship (June -- July 2020) building, developing, and running a new citizen science biodiversity survey. Staring in the eight-minute educational children's programme Milkshake! Monkey's amazing adventures [S2:E2 Rock-Pooling](https://www.my5.tv/milkshake-monkey-s-amazing-adventures/season-2/rock-pooling) which aired on Channel 5 in August 2021.

<center>*We had a wonderful private family rock pool adventure with rock pool expert Christophe. We can't thank you enough for such an enjoyable and informative hour and a half. He was passionate about the sea and all its creatures and is a wealth of knowledge. Our kids absolutely love[ed] it and we left knowing a lot more than we ever did before about the different types of creatures on our coastline. Would highly recommend*</center>

| 
| 

**Artificial light at night - Meta-analysis, University of Exeter:** June 2018 to December 2018

Complete survey of all scientific literature on the topic of ALAN and its impact of ecosystem community and composition, species' abundance and health, and individual animal's physiology and behaviour. Work involving data extraction, summarising literature for others, and handling large volumes of data in excel and R. See publication below.

**FXU Expedition Society:** November 2015 to June 2018

Organising outdoor events requiring multiple steps, including risk assessments, budgeting, itineraries, and leadership skills, such as delegating and working in a team with other committee members. High level of responsibility in the field due to highly changeable environments and many potential risks. Experience leading groups of up to 49 people across Dartmoor, Bodmin moor, the National Three Peaks Challenge (completed in 27.5h) the SW coastal path, and many other landscapes. Promotional work, including the use of social media, direct contact with members and fundraising for local and national charities.

-   **President** : April 2016 to April 2017

-   **Multi-Day Excursion Officer:** April 2017 to April 2018

-   **Walks officer** : November 2015 to April 2016

**Nominated for Non-competitive sport society of the year 2016/17**

<center>"[The Expedition committee] has proved itself to be, without parallel for me, efficient, enthusiastic and hugely collaborative. Here is a team of students who communicate well with each other and with FXU, who share the load fairly between themselves and run events with a keen eye on budget and precise delivery...Statistics are impressive too: whilst their membership numbers have remained largely constant the level of engagement has increased by"</center>

| 
| 

**Walks officer for 'Choose your day' wellbeing project FXU** February 2019 to April 2019

Head hunted and offered a position by the FXU student union to help run a mental wellbeing project, allowing students to experience range of physical activities to manage their mental health. Funded by BUCS and Sport England.

------------------------------------------------------------------------

### Teaching, Mentorship, and Services

**Gradiuate Laison Committee and PGR Board of studies representative** 2020 to present

-   Member of the graduate liaison committee and PGR representative on the department wide Board of Studies; listening to, aggregating, and providing feedback from follow PGRs to improve the experience of PhD students within the Bioscience department.

**Graduate Teaching Assistant** - Durham University & University of Exeter 2018 to present

-   Demonstrating and marking undergraduate and taught masters. Including Behavioural Biology, Evolutionary Biology, Molecular Biology, Genetics, Research Skills, Analysis of Biological Data (with additional responsibility running highly attended after-hours statistics drop in help sessions), Introduction to Invertebrates, and Key Skills in Biology. PGR Maths and Stats tutor providing 1:1 statistics and R coding guidance for third year dissertations.

-   Designed and ran of two PGR Masterclasses for 2nd and 3rd year undergraduates. (1) 'Is a PhD right for you?' -- mentorship and guidance for prospective PGRs. (2) 'My first genome' -- Introduction to command line bioinformatics.

**Undergraduate Summer School Mentor, British Ecological Society** July 2021/22

-   Leading role as a mentor for a week long summer school for undergraduate students studying ecology.
-   Supporting and guiding a personal mentor group through the week and providing wider educational and career advice to the whole cohort. 
-   Planned and presented workshop to provide [an introduction to R](https://christophepatterson.github.io/Introduction_to_R.html), hosted multiple wildlife walks, and shadowed bat, moth, and meadow monitoring sessions.


------------------------------------------------------------------------

### Skills and Other Qualifications

**Outdoor First Aid - Basic --Cornwall First Aid:** Certificate valid until July 2022

One day course covering the basic essentials required to provide emergency care to a casualty. Received training in a range of first aid skills including: The ability to act safely and effectively when an accident or emergency occurs, the treatment and priorities of care for an unconscious casualty, the recognition of cardiac arrest and delivery of Cardiopulmonary Resuscitation (CPR), and to recognise and safely treat a casualty who is choking and/or bleeding.

**IT-skills**

Strong experience with R and RStudio, Microsoft Word, Excel, and PowerPoint. Confident use of command line and Slurm workload manger. Bioinformatics tools - adegenet, bcftools, beast, Blobtools2, busco, bwa, Hifiasm, LEA. RAxML, mitohifi, PAUP, stacks, vcfR. and more. Experience with Python, Adobe Acrobat DC, Matlab, GIS, Adobe After-effects, Paint.net, and Audacity.

**Navigation, Outdoor and Mountain Experience Airienteers Jan 1996 to present**

Organising and competing in numerous orienteering events in urban and rural areas. Complete confidence in map navigation and compass use. Knowledge and experience of multiple environmental hazards and the appropriate actions to minimise risk. Long-time and tested experience kayaking, canoeing, climbing, skiing, fellrunning, surfing and sailing.

------------------------------------------------------------------------

### Other Information

Outside of university and work I enjoy a variety of extreme sports, such as hiking, climbing (I recently summited the 11,000ft alpine peak, the Aiguille de Dibona), skiing, white water canoeing, orienteering (a member of Airienteers), surfing, and sailing as well as more traditional sports such as hockey and football. I have also taught myself the guitar for over 5 years and have performed at multiple open mic nights. My passions include live music events and learning more about the world around me.

------------------------------------------------------------------------

### References

**Dr Regan Early**

Senior Lecturer in Conservation Biology, Daphne du Maurier Building, University of Exeter, Penryn, Cornwall TR10 9FE Email: [r.early\@exeter.ac.uk](mailto:r.early@exeter.ac.uk) Tel: +44 (0)1326 259289

**Dr Jonathan Drury** Associate Professor in the Department of Biosciences, Biosciences, Durham University, Stockton Rd, Durham DH1 3LE Email: [jonathan.p.drury\@durham.ac.uk](mailto:jonathan.p.drury@durham.ac.uk) Tel +44 (0) 191 33 41348
